# Generated by Django 5.2.14 on 2026-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trk', '0003_userprofile_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notify_docs',
            field=models.BooleanField(default=True, help_text='Remind about expiring documents'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_fuel',
            field=models.BooleanField(default=False, help_text='Weekly fuel summary'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_service',
            field=models.BooleanField(default=True, help_text='Remind about upcoming service'),
        ),
    ]
